"""Initial schema with all models

Revision ID: 502e2ba3bd52
Revises: 
Create Date: 2025-11-22 18:07:09.941184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '502e2ba3bd52'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grammar_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('cefr_level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefrlevel'), nullable=False),
    sa.Column('prerequisite_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('rule_description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_grammar_topic_id'), 'grammar_topic', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('preferred_cefr_level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefrlevel'), nullable=False),
    sa.Column('daily_goal_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('error_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('error_category', sa.Enum('CASE_ERROR', 'GENDER_AGREEMENT', 'VERB_CONJUGATION', 'WORD_ORDER', 'SPELLING', 'VOCABULARY', 'ACCENT', 'OTHER', name='errorcategory'), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('correction', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['grammar_topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_log_date'), 'error_log', ['date'], unique=False)
    op.create_index(op.f('ix_error_log_id'), 'error_log', ['id'], unique=False)
    op.create_index(op.f('ix_error_log_topic_id'), 'error_log', ['topic_id'], unique=False)
    op.create_index(op.f('ix_error_log_user_id'), 'error_log', ['user_id'], unique=False)
    op.create_table('exercise_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('exercise_type', sa.Enum('VOCABULARY_CR_EN', 'VOCABULARY_EN_CR', 'VOCABULARY_FILL_BLANK', 'CONVERSATION', 'GRAMMAR', 'SENTENCE_CONSTRUCTION', 'READING', 'DIALOGUE', 'TRANSLATION_CR_EN', 'TRANSLATION_EN_CR', name='exercisetype'), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('exercises_completed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', 'exercise_type', name='uq_user_date_type')
    )
    op.create_index(op.f('ix_exercise_log_date'), 'exercise_log', ['date'], unique=False)
    op.create_index(op.f('ix_exercise_log_id'), 'exercise_log', ['id'], unique=False)
    op.create_index(op.f('ix_exercise_log_user_id'), 'exercise_log', ['user_id'], unique=False)
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exercise_type', sa.Enum('VOCABULARY_CR_EN', 'VOCABULARY_EN_CR', 'VOCABULARY_FILL_BLANK', 'CONVERSATION', 'GRAMMAR', 'SENTENCE_CONSTRUCTION', 'READING', 'DIALOGUE', 'TRANSLATION_CR_EN', 'TRANSLATION_EN_CR', name='exercisetype'), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_id'), 'session', ['id'], unique=False)
    op.create_index(op.f('ix_session_user_id'), 'session', ['user_id'], unique=False)
    op.create_table('topic_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('mastery_score', sa.Integer(), nullable=False),
    sa.Column('times_practiced', sa.Integer(), nullable=False),
    sa.Column('last_practiced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['grammar_topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_id', name='uq_user_topic')
    )
    op.create_index(op.f('ix_topic_progress_id'), 'topic_progress', ['id'], unique=False)
    op.create_index(op.f('ix_topic_progress_topic_id'), 'topic_progress', ['topic_id'], unique=False)
    op.create_index(op.f('ix_topic_progress_user_id'), 'topic_progress', ['user_id'], unique=False)
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('croatian', sa.String(length=200), nullable=False),
    sa.Column('english', sa.String(length=200), nullable=False),
    sa.Column('part_of_speech', sa.Enum('NOUN', 'VERB', 'ADJECTIVE', 'ADVERB', 'PRONOUN', 'PREPOSITION', 'CONJUNCTION', 'INTERJECTION', 'NUMERAL', 'PARTICLE', 'PHRASE', name='partofspeech'), nullable=False),
    sa.Column('gender', sa.Enum('MASCULINE', 'FEMININE', 'NEUTER', name='gender'), nullable=True),
    sa.Column('cefr_level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefrlevel'), nullable=False),
    sa.Column('mastery_score', sa.Integer(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('wrong_count', sa.Integer(), nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_croatian'), 'word', ['croatian'], unique=False)
    op.create_index(op.f('ix_word_english'), 'word', ['english'], unique=False)
    op.create_index(op.f('ix_word_id'), 'word', ['id'], unique=False)
    op.create_index(op.f('ix_word_user_id'), 'word', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_user_id'), table_name='word')
    op.drop_index(op.f('ix_word_id'), table_name='word')
    op.drop_index(op.f('ix_word_english'), table_name='word')
    op.drop_index(op.f('ix_word_croatian'), table_name='word')
    op.drop_table('word')
    op.drop_index(op.f('ix_topic_progress_user_id'), table_name='topic_progress')
    op.drop_index(op.f('ix_topic_progress_topic_id'), table_name='topic_progress')
    op.drop_index(op.f('ix_topic_progress_id'), table_name='topic_progress')
    op.drop_table('topic_progress')
    op.drop_index(op.f('ix_session_user_id'), table_name='session')
    op.drop_index(op.f('ix_session_id'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_exercise_log_user_id'), table_name='exercise_log')
    op.drop_index(op.f('ix_exercise_log_id'), table_name='exercise_log')
    op.drop_index(op.f('ix_exercise_log_date'), table_name='exercise_log')
    op.drop_table('exercise_log')
    op.drop_index(op.f('ix_error_log_user_id'), table_name='error_log')
    op.drop_index(op.f('ix_error_log_topic_id'), table_name='error_log')
    op.drop_index(op.f('ix_error_log_id'), table_name='error_log')
    op.drop_index(op.f('ix_error_log_date'), table_name='error_log')
    op.drop_table('error_log')
    op.drop_table('user')
    op.drop_index(op.f('ix_grammar_topic_id'), table_name='grammar_topic')
    op.drop_table('grammar_topic')
    # ### end Alembic commands ###
