"""add_correct_streak_to_word

Revision ID: 6f2fb341c2b4
Revises: 502e2ba3bd52
Create Date: 2025-11-22 21:58:04.453348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f2fb341c2b4'
down_revision: Union[str, None] = '502e2ba3bd52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('correct_streak', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word', 'correct_streak')
    # ### end Alembic commands ###
